INFO:     Will watch for changes in these directories: ['/Users/yuki/Desktop/rag chatbot2/backend']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [12386] using WatchFiles
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/proto/fields.py'. Reloading...
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given
INFO:     Started server process [12419]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/google/generativeai/text.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/gapic_version.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1/types/generative_service.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [12419]
INFO: Using OpenAI embeddings: text-embedding-3-small
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given
INFO:     Started server process [12442]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO: Using OpenAI embeddings: text-embedding-3-small
INFO:     127.0.0.1:50636 - "GET /health HTTP/1.1" 200 OK
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/google/protobuf/unknown_fields.py', 'venv/lib/python3.9/site-packages/google/protobuf/api_pb2.py', 'venv/lib/python3.9/site-packages/google/protobuf/timestamp_pb2.py', 'venv/lib/python3.9/site-packages/google/protobuf/__init__.py', 'venv/lib/python3.9/site-packages/google/protobuf/duration_pb2.py', 'venv/lib/python3.9/site-packages/google/protobuf/proto_builder.py', 'venv/lib/python3.9/site-packages/google/protobuf/message_factory.py', 'venv/lib/python3.9/site-packages/google/protobuf/empty_pb2.py', 'venv/lib/python3.9/site-packages/google/protobuf/service.py', 'venv/lib/python3.9/site-packages/google/protobuf/wrappers_pb2.py', 'venv/lib/python3.9/site-packages/google/protobuf/field_mask_pb2.py', 'venv/lib/python3.9/site-packages/google/protobuf/any_pb2.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [12442]
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given
INFO:     Started server process [12511]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/google/protobuf/message.py', 'venv/lib/python3.9/site-packages/proto/utils.py', 'venv/lib/python3.9/site-packages/google/protobuf/struct_pb2.py', 'venv/lib/python3.9/site-packages/google/protobuf/text_format.py', 'venv/lib/python3.9/site-packages/google/protobuf/pyext/cpp_message.py', 'venv/lib/python3.9/site-packages/google/protobuf/json_format.py', 'venv/lib/python3.9/site-packages/google/protobuf/internal/decoder.py', 'venv/lib/python3.9/site-packages/google/protobuf/descriptor_pb2.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [12511]
INFO: Using OpenAI embeddings: text-embedding-3-small
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given
INFO:     Started server process [12542]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/proto/primitives.py', 'venv/lib/python3.9/site-packages/google/protobuf/internal/type_checkers.py', 'venv/lib/python3.9/site-packages/google/protobuf/descriptor_database.py', 'venv/lib/python3.9/site-packages/proto/__init__.py', 'venv/lib/python3.9/site-packages/google/protobuf/internal/message_listener.py', 'venv/lib/python3.9/site-packages/google/protobuf/descriptor.py', 'venv/lib/python3.9/site-packages/google/protobuf/internal/_parameterized.py', 'venv/lib/python3.9/site-packages/google/protobuf/pyext/__init__.py', 'venv/lib/python3.9/site-packages/google/protobuf/internal/python_message.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [12542]
INFO: Using OpenAI embeddings: text-embedding-3-small
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/google/api_core/retry_async.py', 'venv/lib/python3.9/site-packages/google/protobuf/internal/builder.py', 'venv/lib/python3.9/site-packages/google/protobuf/descriptor_pool.py', 'venv/lib/python3.9/site-packages/google/protobuf/service_reflection.py', 'venv/lib/python3.9/site-packages/google/protobuf/internal/enum_type_wrapper.py', 'venv/lib/python3.9/site-packages/google/protobuf/internal/containers.py'. Reloading...
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given
INFO:     Started server process [12580]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/google/api_core/path_template.py', 'venv/lib/python3.9/site-packages/google/api_core/client_options.py', 'venv/lib/python3.9/site-packages/grpc_status/rpc_status.py', 'venv/lib/python3.9/site-packages/google/api_core/universe.py', 'venv/lib/python3.9/site-packages/google/api_core/gapic_v1/__init__.py', 'venv/lib/python3.9/site-packages/google/api_core/operations_v1/pagers.py', 'venv/lib/python3.9/site-packages/google/api_core/bidi.py', 'venv/lib/python3.9/site-packages/google/api_core/gapic_v1/routing_header.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [12580]
INFO: Using OpenAI embeddings: text-embedding-3-small
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/google/api_core/__init__.py', 'venv/lib/python3.9/site-packages/google/api_core/rest_streaming_async.py', 'venv/lib/python3.9/site-packages/langchain_google_genai/embeddings.py', 'venv/lib/python3.9/site-packages/google/api_core/operations_v1/operations_client_config.py', 'venv/lib/python3.9/site-packages/proto/marshal/marshal.py', 'venv/lib/python3.9/site-packages/google/api_core/operations_v1/operations_rest_client_async.py', 'venv/lib/python3.9/site-packages/grpc_status/_common.py', 'venv/lib/python3.9/site-packages/langchain_google_genai/chat_models.py'. Reloading...
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given
INFO:     Started server process [12645]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/google/api_core/iam.py', 'venv/lib/python3.9/site-packages/google/generativeai/utils.py', 'venv/lib/python3.9/site-packages/google/api_core/gapic_v1/client_info.py', 'venv/lib/python3.9/site-packages/google/api_core/exceptions.py', 'venv/lib/python3.9/site-packages/grpc_status/__init__.py', 'venv/lib/python3.9/site-packages/google/api_core/operations_v1/operations_client.py', 'venv/lib/python3.9/site-packages/google/api_core/page_iterator.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [12645]
INFO: Using OpenAI embeddings: text-embedding-3-small
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_vendor/packaging/_structures.py', 'venv/lib/python3.9/site-packages/google/api_core/operations_v1/abstract_operations_client.py', 'venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/__init__.py', 'venv/lib/python3.9/site-packages/google/api_core/gapic_v1/method_async.py', 'venv/lib/python3.9/site-packages/pip/_vendor/requests/exceptions.py', 'venv/lib/python3.9/site-packages/pip/_vendor/packaging/version.py', 'venv/lib/python3.9/site-packages/pip/_vendor/packaging/tags.py', 'venv/lib/python3.9/site-packages/pip/_vendor/platformdirs/__main__.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_vendor/rich/_loop.py', 'venv/lib/python3.9/site-packages/langchain_google_genai/llms.py', 'venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/serialize.py', 'venv/lib/python3.9/site-packages/pip/_vendor/tomli/_parser.py', 'venv/lib/python3.9/site-packages/langchain_google_genai/google_vector_store.py', 'venv/lib/python3.9/site-packages/langchain_google_genai/genai_aqa.py', 'venv/lib/python3.9/site-packages/pip/_vendor/msgpack/ext.py', 'venv/lib/python3.9/site-packages/pip/_internal/self_outdated_check.py'. Reloading...
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_vendor/packaging/_tokenizer.py', 'venv/lib/python3.9/site-packages/pip/_vendor/tomli_w/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/packaging/metadata.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_vendor/platformdirs/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/requests/models.py', 'venv/lib/python3.9/site-packages/pip/_vendor/packaging/_manylinux.py', 'venv/lib/python3.9/site-packages/pip/_vendor/packaging/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/platformdirs/macos.py', 'venv/lib/python3.9/site-packages/pip/_vendor/tomli/_re.py', 'venv/lib/python3.9/site-packages/pip/_internal/configuration.py', 'venv/lib/python3.9/site-packages/langchain_google_genai/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/packaging/specifiers.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/progress.py', 'venv/lib/python3.9/site-packages/pip/_vendor/requests/certs.py', 'venv/lib/python3.9/site-packages/pip/__pip-runner__.py'. Reloading...
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/__init__.py', 'venv/lib/python3.9/site-packages/pip/_internal/pyproject.py', 'venv/lib/python3.9/site-packages/pip/_vendor/requests/hooks.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/bar.py', 'venv/lib/python3.9/site-packages/pip/_vendor/requests/help.py', 'venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/wrapper.py', 'venv/lib/python3.9/site-packages/pip/_vendor/platformdirs/version.py', 'venv/lib/python3.9/site-packages/pip/_internal/main.py'. Reloading...
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given
INFO:     Started server process [12738]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_vendor/packaging/markers.py', 'venv/lib/python3.9/site-packages/pip/_vendor/tomli/_types.py', 'venv/lib/python3.9/site-packages/pip/_vendor/requests/auth.py', 'venv/lib/python3.9/site-packages/pip/_vendor/packaging/utils.py', 'venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/cache.py', 'venv/lib/python3.9/site-packages/pip/_vendor/requests/adapters.py', 'venv/lib/python3.9/site-packages/pip/_internal/cache.py', 'venv/lib/python3.9/site-packages/langchain_google_genai/_common.py', 'venv/lib/python3.9/site-packages/pip/_internal/exceptions.py', 'venv/lib/python3.9/site-packages/pip/_vendor/requests/status_codes.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [12738]
INFO: Using OpenAI embeddings: text-embedding-3-small
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_vendor/requests/packages.py', 'venv/lib/python3.9/site-packages/pip/_vendor/tomli/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/reporters.py', 'venv/lib/python3.9/site-packages/pip/_vendor/requests/cookies.py', 'venv/lib/python3.9/site-packages/pip/_internal/wheel_builder.py', 'venv/lib/python3.9/site-packages/pip/__main__.py', 'venv/lib/python3.9/site-packages/pip/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/__init__.py', 'venv/lib/python3.9/site-packages/google/generativeai/types/answer_types.py', 'venv/lib/python3.9/site-packages/pip/_vendor/requests/compat.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/diagnose.py', 'venv/lib/python3.9/site-packages/pip/_vendor/requests/_internal_utils.py'. Reloading...
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_vendor/msgpack/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/structs.py', 'venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/adapter.py', 'venv/lib/python3.9/site-packages/pip/_vendor/packaging/_musllinux.py', 'venv/lib/python3.9/site-packages/pip/_vendor/platformdirs/unix.py', 'venv/lib/python3.9/site-packages/google/generativeai/types/citation_types.py', 'venv/lib/python3.9/site-packages/pip/_vendor/platformdirs/android.py', 'venv/lib/python3.9/site-packages/pip/_vendor/distlib/compat.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/styled.py', 'venv/lib/python3.9/site-packages/pip/_internal/build_env.py', 'venv/lib/python3.9/site-packages/pip/_vendor/distlib/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/requests/api.py'. Reloading...
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/filewrapper.py', 'venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/heuristics.py', 'venv/lib/python3.9/site-packages/pip/_vendor/distlib/resources.py', 'venv/lib/python3.9/site-packages/pip/_vendor/requests/__version__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/platformdirs/api.py', 'venv/lib/python3.9/site-packages/pip/_vendor/msgpack/fallback.py', 'venv/lib/python3.9/site-packages/pip/_vendor/distlib/util.py', 'venv/lib/python3.9/site-packages/pip/_vendor/requests/structures.py', 'venv/lib/python3.9/site-packages/pip/_vendor/requests/utils.py'. Reloading...
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given
INFO:     Started server process [12818]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/google/generativeai/discuss.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/_wrap.py', 'venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/_cmd.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/requests/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/packaging/requirements.py', 'venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/controller.py', 'venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/providers.py', 'venv/lib/python3.9/site-packages/pip/_vendor/packaging/_elffile.py', 'venv/lib/python3.9/site-packages/pip/_vendor/platformdirs/windows.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [12818]
INFO: Using OpenAI embeddings: text-embedding-3-small
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given
INFO:     Started server process [12858]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_internal/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/scope.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/abc.py', 'venv/lib/python3.9/site-packages/pip/_vendor/packaging/_parser.py', 'venv/lib/python3.9/site-packages/pip/_vendor/requests/sessions.py', 'venv/lib/python3.9/site-packages/pip/_internal/locations/_distutils.py', 'venv/lib/python3.9/site-packages/pip/_vendor/distlib/scripts.py', 'venv/lib/python3.9/site-packages/pip/_vendor/tomli_w/_writer.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [12858]
INFO: Using OpenAI embeddings: text-embedding-3-small
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_vendor/truststore/_windows.py', 'venv/lib/python3.9/site-packages/pip/_internal/req/req_dependency_group.py', 'venv/lib/python3.9/site-packages/pip/_vendor/distro/__main__.py', 'venv/lib/python3.9/site-packages/pip/_internal/metadata/_json.py', 'venv/lib/python3.9/site-packages/pip/_internal/req/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/emoji.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/cells.py', 'venv/lib/python3.9/site-packages/pip/_vendor/dependency_groups/__main__.py', 'venv/lib/python3.9/site-packages/pip/_internal/locations/_sysconfig.py', 'venv/lib/python3.9/site-packages/pip/_vendor/dependency_groups/_lint_dependency_groups.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_internal/cli/status_codes.py', 'venv/lib/python3.9/site-packages/pip/_internal/operations/prepare.py', 'venv/lib/python3.9/site-packages/pip/_vendor/certifi/__main__.py', 'venv/lib/python3.9/site-packages/pip/_internal/req/req_file.py', 'venv/lib/python3.9/site-packages/pip/_internal/cli/spinners.py', 'venv/lib/python3.9/site-packages/pip/_vendor/dependency_groups/__init__.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_vendor/rich/_export_format.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/logging.py', 'venv/lib/python3.9/site-packages/pip/_internal/cli/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/_emoji_codes.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/pager.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/idna/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/distro/distro.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/status.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pygments/token.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pygments/formatter.py', 'venv/lib/python3.9/site-packages/pip/_internal/operations/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pygments/style.py', 'venv/lib/python3.9/site-packages/pip/_vendor/truststore/_api.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/exceptions.py', 'venv/lib/python3.9/site-packages/pip/_internal/commands/completion.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/json.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/containers.py', 'venv/lib/python3.9/site-packages/pip/_vendor/certifi/core.py', 'venv/lib/python3.9/site-packages/pip/_internal/locations/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/themes.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/region.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/table.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pygments/modeline.py', 'venv/lib/python3.9/site-packages/pip/_internal/cli/progress_bars.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_vendor/rich/traceback.py', 'venv/lib/python3.9/site-packages/pip/_internal/cli/index_command.py', 'venv/lib/python3.9/site-packages/pip/_internal/commands/uninstall.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/tree.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/_timer.py', 'venv/lib/python3.9/site-packages/pip/_internal/req/req_uninstall.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pygments/plugin.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/markup.py'. Reloading...
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given
INFO:     Started server process [12923]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_vendor/rich/filesize.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/panel.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/layout.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/_ratio.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/live.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/constrain.py', 'venv/lib/python3.9/site-packages/pip/_internal/commands/cache.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/_log_render.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/terminal_theme.py', 'venv/lib/python3.9/site-packages/pip/_internal/cli/main.py', 'venv/lib/python3.9/site-packages/pip/_internal/cli/main_parser.py', 'venv/lib/python3.9/site-packages/pip/_vendor/certifi/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/truststore/_ssl_constants.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/protocol.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [12923]
INFO: Using OpenAI embeddings: text-embedding-3-small
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_vendor/idna/intranges.py', 'venv/lib/python3.9/site-packages/pip/_internal/network/lazy_wheel.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_vendor/rich/padding.py', 'venv/lib/python3.9/site-packages/pip/_vendor/truststore/__init__.py', 'venv/lib/python3.9/site-packages/pip/_internal/network/auth.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pygments/filter.py', 'venv/lib/python3.9/site-packages/pip/_internal/commands/wheel.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/align.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pygments/sphinxext.py', 'venv/lib/python3.9/site-packages/pip/_vendor/dependency_groups/_implementation.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/screen.py', 'venv/lib/python3.9/site-packages/pip/_vendor/idna/idnadata.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/_extension.py', 'venv/lib/python3.9/site-packages/pip/_vendor/truststore/_openssl.py', 'venv/lib/python3.9/site-packages/pip/_internal/commands/__init__.py', 'venv/lib/python3.9/site-packages/pip/_internal/cli/command_context.py', 'venv/lib/python3.9/site-packages/pip/_internal/metadata/pkg_resources.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/rule.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/prompt.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/box.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pygments/console.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/default_styles.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/_inspect.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/poolmanager.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/columns.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/connectionpool.py', 'venv/lib/python3.9/site-packages/pip/_internal/cli/parser.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/_version.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/highlighter.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/_pick.py', 'venv/lib/python3.9/site-packages/pip/_vendor/idna/package_data.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_internal/network/cache.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/file_proxy.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py', 'venv/lib/python3.9/site-packages/pip/_internal/network/xmlrpc.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pygments/__main__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/_null_file.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/color_triplet.py', 'venv/lib/python3.9/site-packages/pip/_internal/req/req_install.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/_palettes.py', 'venv/lib/python3.9/site-packages/pip/_vendor/idna/uts46data.py', 'venv/lib/python3.9/site-packages/pip/_vendor/idna/core.py', 'venv/lib/python3.9/site-packages/pip/_internal/cli/req_command.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_impl.py'. Reloading...
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given
INFO:     Started server process [12995]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_vendor/rich/progress_bar.py', 'venv/lib/python3.9/site-packages/pip/_internal/cli/base_command.py', 'venv/lib/python3.9/site-packages/pip/_internal/locations/base.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/jupyter.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/connection.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/theme.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/_collections.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/pretty.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/_fileno.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/_emoji_replace.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/_windows.py', 'venv/lib/python3.9/site-packages/pip/_internal/commands/hash.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/measure.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pygments/util.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/syntax.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pygments/__init__.py', 'venv/lib/python3.9/site-packages/pip/_internal/commands/check.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/request.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/text.py', 'venv/lib/python3.9/site-packages/pip/_internal/operations/check.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/_stack.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/_windows_renderer.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/color.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/segment.py', 'venv/lib/python3.9/site-packages/pip/_internal/cli/autocompletion.py', 'venv/lib/python3.9/site-packages/pip/_vendor/distro/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/__init__.py', 'venv/lib/python3.9/site-packages/pip/_internal/req/constructors.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/ansi.py', 'venv/lib/python3.9/site-packages/pip/_internal/operations/freeze.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/filepost.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/console.py', 'venv/lib/python3.9/site-packages/pip/_vendor/dependency_groups/_pip_wrapper.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/_spinners.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/_win32_console.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/live_render.py', 'venv/lib/python3.9/site-packages/pip/_internal/commands/search.py', 'venv/lib/python3.9/site-packages/pip/_internal/commands/configuration.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/palette.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pygments/regexopt.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/errors.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/fields.py', 'venv/lib/python3.9/site-packages/pip/_internal/network/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pygments/scanner.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [12995]
INFO: Using OpenAI embeddings: text-embedding-3-small
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_vendor/rich/__main__.py', 'venv/lib/python3.9/site-packages/pip/_internal/commands/download.py', 'venv/lib/python3.9/site-packages/pip/_vendor/dependency_groups/_toml_compat.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/_cell_widths.py', 'venv/lib/python3.9/site-packages/pip/_internal/vcs/versioncontrol.py', 'venv/lib/python3.9/site-packages/pip/_internal/req/req_set.py', 'venv/lib/python3.9/site-packages/pip/_internal/vcs/__init__.py', 'venv/lib/python3.9/site-packages/pip/_internal/metadata/base.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_internal/vcs/mercurial.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_internal/commands/list.py', 'venv/lib/python3.9/site-packages/pip/_internal/cli/cmdoptions.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pygments/unistring.py', 'venv/lib/python3.9/site-packages/pip/_internal/commands/lock.py', 'venv/lib/python3.9/site-packages/pip/_internal/vcs/bazaar.py', 'venv/lib/python3.9/site-packages/pip/_vendor/idna/codec.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pygments/lexer.py', 'venv/lib/python3.9/site-packages/pip/_internal/network/utils.py', 'venv/lib/python3.9/site-packages/pip/_internal/commands/help.py', 'venv/lib/python3.9/site-packages/pip/_internal/metadata/__init__.py'. Reloading...
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_vendor/rich/control.py', 'venv/lib/python3.9/site-packages/pip/_internal/vcs/subversion.py', 'venv/lib/python3.9/site-packages/pip/_vendor/idna/compat.py', 'venv/lib/python3.9/site-packages/pip/_internal/vcs/git.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/style.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_internal/commands/debug.py', 'venv/lib/python3.9/site-packages/pip/_vendor/truststore/_macos.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/repr.py', 'venv/lib/python3.9/site-packages/pip/_internal/network/session.py', 'venv/lib/python3.9/site-packages/pip/_internal/commands/install.py', 'venv/lib/python3.9/site-packages/pip/_vendor/rich/spinner.py', 'venv/lib/python3.9/site-packages/pip/_internal/network/download.py'. Reloading...
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given
INFO:     Started server process [13177]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/deprecated/classic.py', 'venv/lib/python3.9/site-packages/deprecated/sphinx.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [13177]
INFO: Using OpenAI embeddings: text-embedding-3-small
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/deprecated/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/util/_once.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/proto/marshal/__init__.py'. Reloading...
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/util/proxy.py', 'venv/lib/python3.9/site-packages/pip/_internal/operations/build/build_tracker.py', 'venv/lib/python3.9/site-packages/pip/_internal/models/scheme.py', 'venv/lib/python3.9/site-packages/pip/_internal/utils/compat.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/packages/backports/makefile.py', 'venv/lib/python3.9/site-packages/pip/_internal/utils/filetypes.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pygments/styles/_mapping.py', 'venv/lib/python3.9/site-packages/pip/_internal/resolution/legacy/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/appengine.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/__init__.py', 'venv/lib/python3.9/site-packages/pip/_internal/utils/unpacking.py', 'venv/lib/python3.9/site-packages/pip/_internal/utils/compatibility_tags.py', 'venv/lib/python3.9/site-packages/pip/_internal/utils/logging.py', 'venv/lib/python3.9/site-packages/google/protobuf/internal/well_known_types.py', 'venv/lib/python3.9/site-packages/google/protobuf/testdata/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/securetransport.py', 'venv/lib/python3.9/site-packages/pip/_internal/utils/misc.py', 'venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers/resolution.py', 'venv/lib/python3.9/site-packages/pip/_internal/index/package_finder.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/packages/backports/weakref_finalize.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/util/__init__.py', 'venv/lib/python3.9/site-packages/pip/_internal/commands/index.py', 'venv/lib/python3.9/site-packages/proto/modules.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/util/ssltransport.py', 'venv/lib/python3.9/site-packages/pip/_internal/utils/glibc.py', 'venv/lib/python3.9/site-packages/pip/_internal/distributions/installed.py', 'venv/lib/python3.9/site-packages/google/protobuf/internal/__init__.py', 'venv/lib/python3.9/site-packages/google/protobuf/internal/api_implementation.py', 'venv/lib/python3.9/site-packages/proto/version.py', 'venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/requirements.py', 'venv/lib/python3.9/site-packages/pip/_internal/distributions/__init__.py', 'venv/lib/python3.9/site-packages/proto/_file_info.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/proto/marshal/compat.py'. Reloading...
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/opentelemetry/trace/__init__.py', 'venv/lib/python3.9/site-packages/pip/_internal/utils/temp_dir.py', 'venv/lib/python3.9/site-packages/opentelemetry/proto/common/v1/__init__.py', 'venv/lib/python3.9/site-packages/proto/enums.py', 'venv/lib/python3.9/site-packages/opentelemetry/proto/collector/trace/__init__.py', 'venv/lib/python3.9/site-packages/grpc_status/_async.py', 'venv/lib/python3.9/site-packages/proto/datetime_helpers.py', 'venv/lib/python3.9/site-packages/pip/_internal/distributions/base.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/util/connection.py', 'venv/lib/python3.9/site-packages/opentelemetry/util/re.py', 'venv/lib/python3.9/site-packages/proto/marshal/collections/repeated.py', 'venv/lib/python3.9/site-packages/pip/_vendor/packaging/licenses/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/proto/collector/metrics/__init__.py', 'venv/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py', 'venv/lib/python3.9/site-packages/opentelemetry/util/_importlib_metadata.py', 'venv/lib/python3.9/site-packages/opentelemetry/environment_variables/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/proto/common/v1/common_pb2.py', 'venv/lib/python3.9/site-packages/pip/_internal/index/sources.py', 'venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/caches/file_cache.py', 'venv/lib/python3.9/site-packages/google/protobuf/internal/extension_dict.py', 'venv/lib/python3.9/site-packages/pip/_internal/operations/build/wheel_legacy.py', 'venv/lib/python3.9/site-packages/google/protobuf/compiler/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/_securetransport/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pygments/filters/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/caches/__init__.py', 'venv/lib/python3.9/site-packages/pip/_internal/models/target_python.py', 'venv/lib/python3.9/site-packages/opentelemetry/proto/trace/__init__.py', 'venv/lib/python3.9/site-packages/pip/_internal/models/direct_url.py', 'venv/lib/python3.9/site-packages/pip/_internal/utils/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/context/contextvars_context.py', 'venv/lib/python3.9/site-packages/opentelemetry/trace/span.py', 'venv/lib/python3.9/site-packages/opentelemetry/_logs/severity/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/proto/resource/__init__.py', 'venv/lib/python3.9/site-packages/proto/marshal/collections/maps.py', 'venv/lib/python3.9/site-packages/opentelemetry/_logs/_internal/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/baggage/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/context/context.py', 'venv/lib/python3.9/site-packages/google/protobuf/compiler/plugin_pb2.py', 'venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py', 'venv/lib/python3.9/site-packages/opentelemetry/proto/collector/metrics/v1/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/attributes/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/trace/propagation/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/cachecontrol/caches/redis_cache.py', 'venv/lib/python3.9/site-packages/pip/_internal/utils/_jaraco_text.py', 'venv/lib/python3.9/site-packages/opentelemetry/util/types.py', 'venv/lib/python3.9/site-packages/google/protobuf/symbol_database.py', 'venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers/criterion.py', 'venv/lib/python3.9/site-packages/opentelemetry/proto/resource/v1/__init__.py', 'venv/lib/python3.9/site-packages/pip/_internal/resolution/base.py', 'venv/lib/python3.9/site-packages/opentelemetry/trace/propagation/tracecontext.py', 'venv/lib/python3.9/site-packages/google/api_core/operation_async.py', 'venv/lib/python3.9/site-packages/opentelemetry/proto/collector/metrics/v1/metrics_service_pb2_grpc.py', 'venv/lib/python3.9/site-packages/proto/_package_info.py', 'venv/lib/python3.9/site-packages/opentelemetry/util/_providers.py', 'venv/lib/python3.9/site-packages/opentelemetry/proto/__init__.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/opentelemetry/proto/metrics/v1/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/proto/trace/v1/trace_pb2.py', 'venv/lib/python3.9/site-packages/opentelemetry/proto/metrics/v1/metrics_pb2.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/opentelemetry/_events/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/proto/collector/metrics/v1/metrics_service_pb2.py', 'venv/lib/python3.9/site-packages/opentelemetry/trace/status.py', 'venv/lib/python3.9/site-packages/opentelemetry/context/__init__.py', 'venv/lib/python3.9/site-packages/proto/marshal/collections/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/baggage/propagation/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/proto/logs/v1/logs_pb2.py', 'venv/lib/python3.9/site-packages/opentelemetry/proto/version/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/proto/collector/__init__.py'. Reloading...
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/google/api_core/page_iterator_async.py', 'venv/lib/python3.9/site-packages/opentelemetry/proto/metrics/__init__.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_vendor/msgpack/exceptions.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/opentelemetry/proto/common/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/util/_decorator.py', 'venv/lib/python3.9/site-packages/opentelemetry/proto/resource/v1/resource_pb2.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_internal/operations/install/wheel.py', 'venv/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py', 'venv/lib/python3.9/site-packages/pip/_internal/metadata/importlib/_compat.py', 'venv/lib/python3.9/site-packages/pip/_internal/models/search_scope.py', 'venv/lib/python3.9/site-packages/pip/_internal/utils/entrypoints.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/util/queue.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/socks.py', 'venv/lib/python3.9/site-packages/pip/_internal/index/__init__.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pygments/formatters/_mapping.py', 'venv/lib/python3.9/site-packages/pip/_internal/utils/urls.py', 'venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/base.py', 'venv/lib/python3.9/site-packages/google/protobuf/source_context_pb2.py', 'venv/lib/python3.9/site-packages/pip/_internal/metadata/importlib/_dists.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/packages/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/util/ssl_match_hostname.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_internal/operations/install/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/_securetransport/bindings.py', 'venv/lib/python3.9/site-packages/google/protobuf/util/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/ntlmpool.py', 'venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers/exceptions.py', 'venv/lib/python3.9/site-packages/pip/_internal/utils/datetime.py', 'venv/lib/python3.9/site-packages/pip/_internal/utils/hashes.py', 'venv/lib/python3.9/site-packages/pip/_internal/utils/filesystem.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/proto/message.py', 'venv/lib/python3.9/site-packages/google/protobuf/internal/wire_format.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/_securetransport/low_level.py', 'venv/lib/python3.9/site-packages/google/protobuf/internal/encoder.py', 'venv/lib/python3.9/site-packages/pip/_internal/metadata/importlib/__init__.py', 'venv/lib/python3.9/site-packages/pip/_internal/models/__init__.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/google/protobuf/internal/field_mask.py', 'venv/lib/python3.9/site-packages/pip/_internal/operations/install/editable_legacy.py', 'venv/lib/python3.9/site-packages/pip/_internal/utils/deprecation.py', 'venv/lib/python3.9/site-packages/pip/_vendor/packaging/licenses/_spdx.py', 'venv/lib/python3.9/site-packages/pip/_internal/models/pylock.py', 'venv/lib/python3.9/site-packages/pip/_internal/operations/build/wheel.py', 'venv/lib/python3.9/site-packages/pip/_internal/models/wheel.py', 'venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py', 'venv/lib/python3.9/site-packages/pip/_internal/operations/build/metadata_editable.py', 'venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/__init__.py', 'venv/lib/python3.9/site-packages/pip/_internal/models/installation_report.py', 'venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/util/request.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/packages/six.py', 'venv/lib/python3.9/site-packages/pip/_internal/utils/setuptools_build.py', 'venv/lib/python3.9/site-packages/pip/_internal/commands/show.py', 'venv/lib/python3.9/site-packages/pip/_internal/models/format_control.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/util/response.py', 'venv/lib/python3.9/site-packages/pip/_internal/operations/build/wheel_editable.py', 'venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/provider.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_internal/models/candidate.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_internal/operations/build/metadata.py', 'venv/lib/python3.9/site-packages/pip/_internal/models/link.py', 'venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers/abstract.py', 'venv/lib/python3.9/site-packages/pip/_internal/operations/build/metadata_legacy.py', 'venv/lib/python3.9/site-packages/pip/_internal/utils/wheel.py', 'venv/lib/python3.9/site-packages/google/protobuf/internal/testing_refleaks.py', 'venv/lib/python3.9/site-packages/pip/_internal/operations/build/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pygments/lexers/python.py', 'venv/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/reporter.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pygments/lexers/_mapping.py', 'venv/lib/python3.9/site-packages/pip/_internal/distributions/wheel.py', 'venv/lib/python3.9/site-packages/pip/_internal/metadata/importlib/_envs.py', 'venv/lib/python3.9/site-packages/pip/_internal/models/index.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/__init__.py', 'venv/lib/python3.9/site-packages/pip/_internal/utils/virtualenv.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/util/wait.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/util/retry.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/_appengine_environ.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/util/ssl_.py', 'venv/lib/python3.9/site-packages/pip/_internal/utils/retry.py', 'venv/lib/python3.9/site-packages/pip/_internal/utils/egg_link.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pygments/styles/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/util/timeout.py', 'venv/lib/python3.9/site-packages/pip/_internal/models/selection_prefs.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/packages/backports/__init__.py', 'venv/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py', 'venv/lib/python3.9/site-packages/pip/_internal/utils/appdirs.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py', 'venv/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pygments/formatters/__init__.py', 'venv/lib/python3.9/site-packages/pip/_internal/commands/freeze.py', 'venv/lib/python3.9/site-packages/pip/_internal/utils/_log.py', 'venv/lib/python3.9/site-packages/pip/_internal/commands/inspect.py', 'venv/lib/python3.9/site-packages/pip/_internal/utils/packaging.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/opentelemetry/util/http/__init__.py', 'venv/lib/python3.9/site-packages/pip/_internal/index/collector.py', 'venv/lib/python3.9/site-packages/opentelemetry/proto/trace/v1/__init__.py', 'venv/lib/python3.9/site-packages/pip/_internal/utils/direct_url_helpers.py', 'venv/lib/python3.9/site-packages/pip/_internal/resolution/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/pygments/lexers/__init__.py', 'venv/lib/python3.9/site-packages/pip/_vendor/urllib3/util/url.py', 'venv/lib/python3.9/site-packages/google/api_core/rest_helpers.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/google/api_core/operations_v1/pagers_async.py', 'venv/lib/python3.9/site-packages/google/api_core/future/polling.py', 'venv/lib/python3.9/site-packages/google/api_core/operations_v1/transports/rest.py', 'venv/lib/python3.9/site-packages/google/api_core/general_helpers.py', 'venv/lib/python3.9/site-packages/google/api_core/future/_helpers.py', 'venv/lib/python3.9/site-packages/google/api_core/rest_streaming.py', 'venv/lib/python3.9/site-packages/google/api_core/version.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/google/api_core/operations_v1/abstract_operations_base_client.py', 'venv/lib/python3.9/site-packages/google/api_core/gapic_v1/config_async.py', 'venv/lib/python3.9/site-packages/google/api_core/timeout.py', 'venv/lib/python3.9/site-packages/google/api_core/retry/__init__.py', 'venv/lib/python3.9/site-packages/google/api_core/extended_operation.py', 'venv/lib/python3.9/site-packages/google/api_core/operation.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/google/api_core/client_info.py', 'venv/lib/python3.9/site-packages/google/api_core/version_header.py', 'venv/lib/python3.9/site-packages/google/api_core/grpc_helpers.py', 'venv/lib/python3.9/site-packages/google/api_core/operations_v1/transports/__init__.py', 'venv/lib/python3.9/site-packages/google/api_core/operations_v1/pagers_base.py', 'venv/lib/python3.9/site-packages/google/api_core/retry/retry_unary.py', 'venv/lib/python3.9/site-packages/google/api_core/retry/retry_unary_async.py', 'venv/lib/python3.9/site-packages/google/api_core/operations_v1/transports/rest_asyncio.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/google/api_core/retry/retry_base.py', 'venv/lib/python3.9/site-packages/google/api_core/grpc_helpers_async.py', 'venv/lib/python3.9/site-packages/google/api_core/operations_v1/operations_async_client.py', 'venv/lib/python3.9/site-packages/google/api_core/protobuf_helpers.py', 'venv/lib/python3.9/site-packages/google/api_core/client_logging.py', 'venv/lib/python3.9/site-packages/google/api_core/operations_v1/__init__.py', 'venv/lib/python3.9/site-packages/google/api_core/future/__init__.py', 'venv/lib/python3.9/site-packages/google/api_core/gapic_v1/method.py'. Reloading...
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/importlib_metadata/_adapters.py', 'venv/lib/python3.9/site-packages/proto/marshal/rules/bytes.py', 'venv/lib/python3.9/site-packages/proto/marshal/rules/message.py', 'venv/lib/python3.9/site-packages/opentelemetry/util/http/version.py', 'venv/lib/python3.9/site-packages/importlib_metadata/_meta.py', 'venv/lib/python3.9/site-packages/proto/marshal/rules/struct.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/proto/marshal/rules/dates.py', 'venv/lib/python3.9/site-packages/importlib_metadata/_compat.py', 'venv/lib/python3.9/site-packages/proto/marshal/rules/__init__.py', 'venv/lib/python3.9/site-packages/proto/marshal/rules/enums.py', 'venv/lib/python3.9/site-packages/proto/marshal/rules/stringy_numbers.py', 'venv/lib/python3.9/site-packages/importlib_metadata/_functools.py', 'venv/lib/python3.9/site-packages/importlib_metadata/_collections.py', 'venv/lib/python3.9/site-packages/opentelemetry/util/http/httplib.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/importlib_metadata/_text.py', 'venv/lib/python3.9/site-packages/importlib_metadata/_itertools.py', 'venv/lib/python3.9/site-packages/proto/marshal/rules/wrappers.py', 'venv/lib/python3.9/site-packages/proto/marshal/rules/field_mask.py', 'venv/lib/python3.9/site-packages/importlib_metadata/diagnose.py', 'venv/lib/python3.9/site-packages/opentelemetry/propagators/composite.py', 'venv/lib/python3.9/site-packages/importlib_metadata/__init__.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/opentelemetry/version/__init__.py', 'venv/lib/python3.9/site-packages/importlib_metadata/compat/__init__.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/importlib_metadata/compat/py39.py', 'venv/lib/python3.9/site-packages/importlib_metadata/compat/py311.py', 'venv/lib/python3.9/site-packages/opentelemetry/_logs/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/propagators/textmap.py'. Reloading...
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/opentelemetry/proto/collector/logs/v1/logs_service_pb2.py', 'venv/lib/python3.9/site-packages/opentelemetry/proto/collector/trace/v1/trace_service_pb2_grpc.py', 'venv/lib/python3.9/site-packages/opentelemetry/proto/collector/trace/v1/trace_service_pb2.py', 'venv/lib/python3.9/site-packages/opentelemetry/proto/collector/logs/v1/logs_service_pb2_grpc.py', 'venv/lib/python3.9/site-packages/google/generativeai/retriever.py', 'venv/lib/python3.9/site-packages/google/generativeai/embedding.py', 'venv/lib/python3.9/site-packages/opentelemetry/proto/collector/trace/v1/__init__.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1/gapic_version.py', 'venv/lib/python3.9/site-packages/google/generativeai/types/model_types.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1/types/model_service.py', 'venv/lib/python3.9/site-packages/google/generativeai/types/generation_types.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/gapic_version.py', 'venv/lib/python3.9/site-packages/google/generativeai/version.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1/__init__.py', 'venv/lib/python3.9/site-packages/google/generativeai/models.py', 'venv/lib/python3.9/site-packages/google/generativeai/generative_models.py', 'venv/lib/python3.9/site-packages/google/generativeai/answer.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/gapic_version.py', 'venv/lib/python3.9/site-packages/google/generativeai/types/discuss_types.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage/__init__.py', 'venv/lib/python3.9/site-packages/google/generativeai/types/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1/types/model.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/__init__.py', 'venv/lib/python3.9/site-packages/google/generativeai/types/retriever_types.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1/types/citation.py', 'venv/lib/python3.9/site-packages/google/generativeai/types/content_types.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1/types/safety.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage/gapic_version.py', 'venv/lib/python3.9/site-packages/google/generativeai/types/permission_types.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1/types/__init__.py', 'venv/lib/python3.9/site-packages/google/generativeai/types/safety_types.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1/types/content.py', 'venv/lib/python3.9/site-packages/google/generativeai/types/text_types.py', 'venv/lib/python3.9/site-packages/google/generativeai/permission.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/types/discuss_service.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/types/safety.py', 'venv/lib/python3.9/site-packages/langchain_google_genai/_enums.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/sheets_id.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/command_utils.py', 'venv/lib/python3.9/site-packages/google/generativeai/client.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/types/tuned_model.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/types/__init__.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/compare_cmd.py', 'venv/lib/python3.9/site-packages/google/generativeai/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/types/tuned_model.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/magics.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/gspread_client.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/ipython_env.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/parsed_args_lib.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/types/discuss_service.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/magics_engine.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/model_registry.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/output_utils.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/eval_cmd.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/types/model_service.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1/services/__init__.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/post_process_utils_test_helper.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/ipython_env_impl.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/command.py', 'venv/lib/python3.9/site-packages/langchain_google_genai/_function_utils.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/flag_def.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/types/discuss_service.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/services/__init__.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/run_cmd.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/types/model.py', 'venv/lib/python3.9/site-packages/google/generativeai/string_utils.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/types/generative_service.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/types/safety.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/types/text_service.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/compile_cmd.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/input_utils.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/types/permission.py', 'venv/lib/python3.9/site-packages/google/generativeai/operations.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/types/model.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/types/citation.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/sheets_sanitize_url.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/types/model_service.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/types/permission.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/types/citation.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/types/model_service.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/post_process_utils.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/types/safety.py', 'venv/lib/python3.9/site-packages/google/api_core/future/async_future.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/types/content.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/types/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/bootstrap_gen.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/py_utils.py', 'venv/lib/python3.9/site-packages/google/api_core/retry/retry_streaming_async.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/argument_parser.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/attributes/server_attributes.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/types/retriever_service.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/types/model.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/types/text_service.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/cmd_line_parser.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/attributes/client_attributes.py', 'venv/lib/python3.9/site-packages/google/api_core/datetime_helpers.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/types/citation.py', 'venv/lib/python3.9/site-packages/google/api_core/gapic_v1/config.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/attributes/error_attributes.py', 'venv/lib/python3.9/site-packages/langchain_google_genai/_genai_extension.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/types/text_service.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/text_model.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/attributes/otel_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/attributes/http_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/attributes/network_attributes.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/types/retriever.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/attributes/telemetry_attributes.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/types/permission_service.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/types/__init__.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/sheets_utils.py', 'venv/lib/python3.9/site-packages/google/api_core/retry/retry_streaming.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/types/permission_service.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/attributes/user_agent_attributes.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/html_utils.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/__init__.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/model_service/async_client.py', 'venv/lib/python3.9/site-packages/google/api_core/_rest_streaming_base.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/permission_service/client.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/permission_service/__init__.py', 'venv/lib/python3.9/site-packages/google/api_core/future/base.py', 'venv/lib/python3.9/site-packages/google/api_core/operations_v1/transports/base.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/permission_service/pagers.py'. Reloading...
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/permission_service/async_client.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1/services/model_service/client.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/sqlcommenter_utils.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/lib/llmfn_outputs.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1/services/model_service/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/utils.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/lib/prompt_utils.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/client.py', 'venv/lib/python3.9/site-packages/opentelemetry/propagate/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/discuss_service/async_client.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/permission_service/pagers.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/services/model_service/pagers.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/permission_service/client.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/services/text_service/async_client.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/lib/llmfn_post_process_cmds.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/lib/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/services/discuss_service/client.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/lib/llm_function.py', 'venv/lib/python3.9/site-packages/opentelemetry/metrics/_internal/instrument.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/services/discuss_service/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/services/model_service/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/distro.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/retriever_service/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/discuss_service/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/model_service/client.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/instrumentor.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/model_service/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/discuss_service/client.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/_semconv.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/version.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/attributes/url_attributes.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/lib/llmfn_input_utils.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/text_service/client.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/lib/model.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/permission_service/async_client.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/services/discuss_service/async_client.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1/services/model_service/pagers.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/retriever_service/async_client.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/services/model_service/async_client.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/text_service/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1/services/generative_service/__init__.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/model_service/pagers.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/model_service/client.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/propagators.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/text_service/async_client.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/retriever_service/pagers.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/model_service/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/model_service/pagers.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/services/model_service/client.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/retriever_service/client.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/permission_service/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/discuss_service/client.py', 'venv/lib/python3.9/site-packages/opentelemetry/metrics/_internal/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/text_service/async_client.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/__init__.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/lib/unique_fn.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1/services/generative_service/async_client.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/lib/llmfn_output_row.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1/services/model_service/async_client.py', 'venv/lib/python3.9/site-packages/opentelemetry/metrics/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/text_service/client.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/discuss_service/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/dependencies.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/text_service/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/environment_variables.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/async_client.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/services/text_service/client.py', 'venv/lib/python3.9/site-packages/opentelemetry/metrics/_internal/observation.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/schemas.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/services/text_service/__init__.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/lib/llmfn_inputs_source.py', 'venv/lib/python3.9/site-packages/google/generativeai/notebook/lib/llmfn_post_process.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/discuss_service/async_client.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1/services/generative_service/client.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/bootstrap.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/model_service/async_client.py'. Reloading...
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1/services/model_service/transports/rest.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/retriever_service/transports/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/permission_service/transports/base.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1/services/generative_service/transports/rest.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1/services/generative_service/transports/grpc_asyncio.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/permission_service/transports/grpc.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/text_service/transports/base.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/metrics/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/text_service/transports/grpc.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/permission_service/transports/grpc.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/text_service/transports/rest.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/text_service/transports/grpc_asyncio.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/discuss_service/transports/rest.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/transports/grpc.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/discuss_service/transports/grpc_asyncio.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/trace/__init__.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1/services/model_service/transports/grpc_asyncio.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/attributes/exception_attributes.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/model_service/transports/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1/services/generative_service/transports/base.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/fastapi/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/model_service/transports/base.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/retriever_service/transports/grpc.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/transports/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/metrics/http_metrics.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1/services/model_service/transports/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/exporter/otlp/proto/common/_log_encoder.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/retriever_service/transports/rest.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/model_service/transports/grpc_asyncio.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/permission_service/transports/rest.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/discuss_service/transports/grpc_asyncio.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/fastapi/package.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/discuss_service/transports/rest.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/transports/rest.py', 'venv/lib/python3.9/site-packages/opentelemetry/exporter/otlp/proto/common/__init__.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/opentelemetry/exporter/otlp/proto/grpc/version.py', 'venv/lib/python3.9/site-packages/opentelemetry/exporter/otlp/proto/common/version.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/permission_service/transports/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/discuss_service/transports/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/text_service/transports/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1/services/generative_service/transports/grpc.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/auto_instrumentation/sitecustomize.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/model_service/transports/grpc.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/permission_service/transports/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/retriever_service/transports/base.py', 'venv/lib/python3.9/site-packages/opentelemetry/exporter/otlp/proto/grpc/exporter.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/discuss_service/transports/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/fastapi/version.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/model_service/transports/grpc.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/discuss_service/transports/base.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/text_service/transports/base.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/model_service/transports/grpc_asyncio.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/text_service/transports/grpc.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/discuss_service/transports/grpc.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/permission_service/transports/base.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/discuss_service/transports/base.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/retriever_service/transports/grpc_asyncio.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/model_service/transports/rest.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/resource/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/discuss_service/transports/grpc.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/transports/base.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1/services/model_service/transports/base.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/permission_service/transports/grpc_asyncio.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/text_service/transports/rest.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/text_service/transports/grpc_asyncio.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1/services/model_service/transports/grpc.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/permission_service/transports/rest.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/asgi/types.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1/services/generative_service/transports/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/exporter/otlp/proto/grpc/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/model_service/transports/__init__.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/model_service/transports/base.py'. Reloading...
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/generative_service/transports/grpc_asyncio.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/auto_instrumentation/_load.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/version/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/exporter/otlp/proto/common/metrics_encoder.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta3/services/text_service/transports/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/attributes/service_attributes.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/model_service/transports/rest.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/auto_instrumentation/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta/services/permission_service/transports/grpc_asyncio.py', 'venv/lib/python3.9/site-packages/opentelemetry/exporter/otlp/proto/common/trace_encoder.py'. Reloading...
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given
INFO:     Started server process [13854]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/system_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/pool_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/webengine_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/metrics/process_metrics.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/disk_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/host_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/cicd_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/user_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/cloudevents_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/db_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/oci_attributes.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/services/discuss_service/transports/grpc.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/container_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/log_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/asgi/version.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/environment_variables/__init__.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/services/discuss_service/transports/grpc_asyncio.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/peer_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/http_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/otel_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/network_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/net_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/os_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/metrics/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/faas_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/vcs_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/user_agent_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/aws_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/tls_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/url_attributes.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/services/model_service/transports/grpc_asyncio.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/browser_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/metrics/system_metrics.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/asgi/package.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/exception_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/heroku_attributes.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/services/discuss_service/transports/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/gen_ai_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/feature_flag_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/event_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/thread_attributes.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [13854]
INFO: Using OpenAI embeddings: text-embedding-3-small
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/opentelemetry/sdk/trace/sampling.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/enduser_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/gcp_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/opentracing_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/deployment_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/metrics/faas_metrics.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/server_attributes.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/services/discuss_service/transports/base.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/message_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/service_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/messaging_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/client_attributes.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/services/text_service/transports/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/asgi/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/metrics/http_metrics.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/graphql_attributes.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/services/model_service/transports/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/error_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/metrics/db_metrics.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/code_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/linux_attributes.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/services/discuss_service/transports/rest.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/services/text_service/transports/base.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/metrics/rpc_metrics.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/metrics/dns_metrics.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/cloud_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/metrics/container_metrics.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/services/text_service/transports/grpc.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/process_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/metrics/gen_ai_metrics.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/telemetry_attributes.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/services/model_service/transports/base.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/rpc_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/dns_attributes.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/services/model_service/transports/grpc.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/session_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/metrics/messaging_metrics.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/cpu_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/destination_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/artifact_attributes.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/services/text_service/transports/rest.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/source_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/resources/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/file_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/az_attributes.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/services/text_service/transports/grpc_asyncio.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/k8s_attributes.py', 'venv/lib/python3.9/site-packages/google/ai/generativelanguage_v1beta2/services/model_service/transports/rest.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/other_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/device_attributes.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/_incubating/attributes/test_attributes.py'. Reloading...
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given
INFO:     Started server process [13947]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/opentelemetry/sdk/metrics/_internal/sdk_configuration.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/trace/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/metrics/_internal/exponential_histogram/mapping/errors.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/util/instrumentation.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/version/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/exporter/otlp/proto/common/_internal/trace_encoder/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/metrics/_internal/export/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/_logs/export/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/metrics/view/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/exporter/otlp/proto/common/_internal/_log_encoder/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/metrics/export/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/trace/id_generator.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/_logs/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/metrics/_internal/aggregation.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/error_handler/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/metrics/_internal/measurement.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/_logs/_internal/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/_logs/_internal/export/in_memory_log_exporter.py', 'venv/lib/python3.9/site-packages/opentelemetry/exporter/otlp/proto/common/_internal/metrics_encoder/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/trace/export/in_memory_span_exporter.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/metrics/_internal/measurement_consumer.py', 'venv/lib/python3.9/site-packages/opentelemetry/exporter/otlp/proto/common/_internal/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/metrics/_internal/exponential_histogram/mapping/exponent_mapping.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/metrics/_internal/exceptions.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [13947]
INFO: Using OpenAI embeddings: text-embedding-3-small
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/opentelemetry/sdk/metrics/_internal/metric_reader_storage.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/metrics/_internal/view.py', 'venv/lib/python3.9/site-packages/opentelemetry/exporter/otlp/proto/grpc/_log_exporter/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/trace/export/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/exporter/otlp/proto/grpc/metric_exporter/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/metrics/_internal/exponential_histogram/buckets.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/_logs/_internal/export/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/metrics/_internal/_view_instrument_match.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/util/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/metrics/_internal/exponential_histogram/mapping/ieee_754.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/metrics/_internal/exponential_histogram/mapping/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/exporter/otlp/proto/grpc/trace_exporter/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/metrics/_internal/instrument.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/metrics/_internal/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/_configuration/__init__.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/metrics/_internal/exponential_histogram/mapping/logarithm_mapping.py', 'venv/lib/python3.9/site-packages/opentelemetry/sdk/metrics/_internal/point.py'. Reloading...
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given
INFO:     Started server process [14045]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/bootstrap 2.py', 'venv/lib/python3.9/site-packages/opentelemetry/propagate/__init__ 2.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/version 2.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/__init__ 2.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/bootstrap_gen 2.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/instrumentor 2.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/environment_variables 2.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/_semconv 2.py', 'venv/lib/python3.9/site-packages/opentelemetry/metrics/__init__ 2.py', 'venv/lib/python3.9/site-packages/opentelemetry/semconv/schemas 2.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/propagators 2.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/utils 2.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/sqlcommenter_utils 2.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/distro 2.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/dependencies 2.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [14045]
INFO: Using OpenAI embeddings: text-embedding-3-small
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given
INFO:     Started server process [14105]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/fastapi/version 2.py', 'venv/lib/python3.9/site-packages/opentelemetry/util/http/version 2.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/asgi/version 2.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/fastapi/__init__ 2.py', 'venv/lib/python3.9/site-packages/opentelemetry/util/http/__init__ 2.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/asgi/__init__ 2.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/auto_instrumentation/sitecustomize 2.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/fastapi/package 2.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/asgi/package 2.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/asgi/types 2.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/auto_instrumentation/__init__ 2.py', 'venv/lib/python3.9/site-packages/opentelemetry/instrumentation/auto_instrumentation/_load 2.py', 'venv/lib/python3.9/site-packages/opentelemetry/util/http/httplib 2.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [14105]
INFO: Using OpenAI embeddings: text-embedding-3-small
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given
INFO:     Started server process [14333]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_internal 2/pyproject.py', 'venv/lib/python3.9/site-packages/pip/_internal/__init__.py', 'venv/lib/python3.9/site-packages/pip/_internal 2/exceptions.py', 'venv/lib/python3.9/site-packages/pip/_internal/exceptions.py', 'venv/lib/python3.9/site-packages/pip/_internal/pyproject.py', 'venv/lib/python3.9/site-packages/pip/_internal 2/main.py', 'venv/lib/python3.9/site-packages/pip/_internal/self_outdated_check.py', 'venv/lib/python3.9/site-packages/pip/_internal/build_env.py', 'venv/lib/python3.9/site-packages/pip/_internal 2/__init__.py', 'venv/lib/python3.9/site-packages/pip/_internal/cache.py', 'venv/lib/python3.9/site-packages/pip/_internal/configuration.py', 'venv/lib/python3.9/site-packages/pip/_internal 2/configuration.py', 'venv/lib/python3.9/site-packages/pip/_internal 2/cache.py', 'venv/lib/python3.9/site-packages/pip/_internal 2/self_outdated_check.py', 'venv/lib/python3.9/site-packages/pip/_internal/main.py', 'venv/lib/python3.9/site-packages/pip/_internal 2/build_env.py'. Reloading...
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [14333]
INFO: Using OpenAI embeddings: text-embedding-3-small
WARNING:  WatchFiles detected changes in 'venv/lib/python3.9/site-packages/pip/_internal/network/cache.py', 'venv/lib/python3.9/site-packages/pip/_internal/network/lazy_wheel.py', 'venv/lib/python3.9/site-packages/pip/_internal/network/xmlrpc.py', 'venv/lib/python3.9/site-packages/pip/_internal 2/wheel_builder.py', 'venv/lib/python3.9/site-packages/pip/_internal/wheel_builder.py', 'venv/lib/python3.9/site-packages/pip/_internal/network/session.py', 'venv/lib/python3.9/site-packages/pip/_internal/network/auth.py', 'venv/lib/python3.9/site-packages/pip/_internal/network/__init__.py', 'venv/lib/python3.9/site-packages/pip/_internal/network/utils.py', 'venv/lib/python3.9/site-packages/pip/_internal/network/download.py'. Reloading...
/Users/yuki/Desktop/rag chatbot2/backend/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Failed to send telemetry event ClientStartEvent: capture() takes 1 positional argument but 3 were given
Failed to send telemetry event ClientCreateCollectionEvent: capture() takes 1 positional argument but 3 were given
INFO:     Started server process [14472]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [14472]
INFO: Using OpenAI embeddings: text-embedding-3-small
INFO:     Stopping reloader process [12386]
